import fs from "fs/promises";
import path from "path";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

const ROOT_DIR = process.cwd();
const TARGETS_CONF_PATH = path.join(ROOT_DIR, "conf", "restream.targets.conf");
const NGINX_BIN = path.join(ROOT_DIR, "src", "nginx-1.18.0", "objs", "nginx");
const NGINX_CONF_TEMPLATE = path.join(ROOT_DIR, "conf", "nginx.conf");
const NGINX_CONF = path.join(ROOT_DIR, "run", "nginx.conf");
const NGINX_PID = path.join(ROOT_DIR, "run", "nginx.pid");

export function normalizeRestreamKey(value) {
  return String(value || "").trim();
}

export function buildRestreamTargets({ youtubeKey = "", facebookKey = "" }) {
  const normalizedYoutubeKey = normalizeRestreamKey(youtubeKey);
  const normalizedFacebookKey = normalizeRestreamKey(facebookKey);
  const targets = [];

  if (normalizedYoutubeKey) {
    targets.push({
      provider: "youtube-primary",
      url: `rtmp://a.rtmp.youtube.com/live2/${normalizedYoutubeKey}`
    });
    targets.push({
      provider: "youtube-backup",
      url: `rtmp://b.rtmp.youtube.com/live2/${normalizedYoutubeKey}?backup=1`
    });
  }

  if (normalizedFacebookKey) {
    targets.push({
      provider: "facebook",
      url: `rtmps://live-api-s.facebook.com:443/rtmp/${normalizedFacebookKey}`,
      supported: false
    });
  }

  return targets;
}

export function renderRestreamTargetsConf(targets) {
  const header = [
    "# Generated by /api/restream",
    "# Edit manually if needed, then reload nginx."
  ];

  if (targets.length === 0) {
    return `${header.join("\n")}\n# No active restream targets.\n`;
  }

  const lines = targets.flatMap((target) => [
    `# ${target.provider}`,
    target.supported === false
      ? `# Unsupported in current nginx-rtmp push parser: ${target.url}`
      : `push ${target.url};`
  ]);

  return `${header.join("\n")}\n${lines.join("\n")}\n`;
}

export async function writeRestreamTargets({ youtubeKey = "", facebookKey = "" }) {
  const targets = buildRestreamTargets({ youtubeKey, facebookKey });
  const config = renderRestreamTargetsConf(targets);

  await fs.writeFile(TARGETS_CONF_PATH, config, "utf8");

  return { targets, config };
}

async function getRunningNginxPid() {
  try {
    const rawPid = await fs.readFile(NGINX_PID, "utf8");
    const pid = Number.parseInt(rawPid.trim(), 10);

    if (!Number.isInteger(pid) || pid <= 0) {
      await fs.rm(NGINX_PID, { force: true });
      return null;
    }

    try {
      process.kill(pid, 0);
      return pid;
    } catch {
      await fs.rm(NGINX_PID, { force: true });
      return null;
    }
  } catch {
    return null;
  }
}

async function renderNginxConfig() {
  const template = await fs.readFile(NGINX_CONF_TEMPLATE, "utf8");
  await fs.mkdir(path.dirname(NGINX_CONF), { recursive: true });
  await fs.writeFile(NGINX_CONF, template.replaceAll("__PROJECT_ROOT__", ROOT_DIR), "utf8");
}

export async function reloadNginx() {
  await renderNginxConfig();

  const baseArgs = [
    "-p",
    `${ROOT_DIR}/`,
    "-c",
    NGINX_CONF
  ];

  await execFileAsync(NGINX_BIN, ["-t", ...baseArgs]);

  const pid = await getRunningNginxPid();

  if (pid) {
    await execFileAsync(NGINX_BIN, [...baseArgs, "-s", "reload"]);
    return { mode: "reload", pid };
  }

  await execFileAsync(NGINX_BIN, baseArgs);
  return { mode: "start" };
}
